# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fiapapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrinfiniteloops.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_11B09BC07F294DBC838D1F2E81E25F6A }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_ECECC6D91354431A82E1DFCE90BA677B }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrinfiniteloops.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_11B09BC07F294DBC838D1F2E81E25F6A }}/core.postech8nett:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8F72D3406C064409BE9D87E0E4D0147C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_59BF3B0BFB644BCD83F52C756A5A9010 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_47DC238DB89241788E43BB2386E8EDA4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiapapp'
          slot-name: 'Production'
          images: 'acrinfiniteloops.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_11B09BC07F294DBC838D1F2E81E25F6A }}/core.postech8nett:${{ github.sha }}'
          