# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fiapapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrinfiniteloops.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4C9453DC752143BEB513441BCAEB6553 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_26941D8CD46845528EEA8886411A9EF2 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrinfiniteloops.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4C9453DC752143BEB513441BCAEB6553 }}/acrinfiniteloops/core.postech8nett:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C07217D9F7AA49FAA2DC1A3ECB614DD7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94DFCC8584DC446C91368F1FE259E490 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4251CFBE846B40F8BE2187A1667A6ECD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiapapp'
          slot-name: 'Production'
          images: 'acrinfiniteloops.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4C9453DC752143BEB513441BCAEB6553 }}/acrinfiniteloops/core.postech8nett:${{ github.sha }}'
          