# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fiapapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrinfiniteloops.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6A522BC2E8AB4F6A8FF3D6648AE2E785 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_E4BBD169F7C34A608B741327FADF8BCE }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrinfiniteloops.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6A522BC2E8AB4F6A8FF3D6648AE2E785 }}/acrinfiniteloops/core.postech8nett:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_749DE33B04D64EF59BAED6941D8F52A8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_417260B2EB6C4F1E911C3487C809EE08 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F609D3FC0FF24370AA9E0D11BED1C567 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiapapp'
          slot-name: 'Production'
          images: 'acrinfiniteloops.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6A522BC2E8AB4F6A8FF3D6648AE2E785 }}/acrinfiniteloops/core.postech8nett:${{ github.sha }}'
          